StudentWebSite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views

app_name='music'


urlpatterns = [
    url(r'^$', views.index,name='index'),

    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='detail'),

    

    url(r'^(?P<album_id>[0-9]+)/favorite/$',views.favorite,name='favorite'),
]

music/models.py
from django.db import models

# Create your models here.
class Album(models.Model):
	artist=models.CharField(max_length=250) 
	album_title=models.CharField(max_length=500)
	genre=models.CharField(max_length=100)
	album_logo=models.CharField(max_length=1000)

	def __str__(self):
		return self.album_title+' - '+self.artist

class Song(models.Model):
	album=models.ForeignKey(Album,on_delete=models.CASCADE)
	file_type=models.CharField(max_length=100)
	song_title=models.CharField(max_length=250)
	is_favorite=models.BooleanField(default=False)
	
	def __str__(self):
		return self.song_title

music/views.py
from django.shortcuts import render,get_object_or_404
from django.http import Http404
from .models import Album
from django.template import loader

def index(request):
	all_album=Album.objects.all()		
	return render(request,'music/index.html',{'all_album':all_album})


def detail(request,album_id):
	# album=Album.objects.get(pk=album_id)
	album=get_object_or_404(Album,pk=album_id)
	return render(request,'music/Detail.html',{'album':album})

def favorite(request,album_id):
	album=get_object_or_404(Album,pk=album_id)
	try:
		selected_song=album.song_set.get(pk=request.POST['song'])
	except (KeyError,Song.DoesNotExist):
		return render(request,'music/Detail.html',{
			'album':album,
			'error_message':"You did not select a valid song",
			})
	else:
		selected_song.is_favorite=True
		selected_song.save()
		return render(request,'music/Detail.html',{'album':album})

music/templates/music/Detail.html
{% extends 'music/base.html' %}
<title>{% block title %}Album Details{% endblock %}</title>
{% block body%}
<img src="{{ album.album_logo }}">
<h1>{{ album.album_title }}
<h3>{{ album.artist }}</h3>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
	{% csrf_token %}
	{% for song in album.song_set.all %}
		<input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
		<label for="song{{ forloop.counter }}">
			{{ song.song_title }}
			{% if song.is_favorite %}
				<img width="20" height="20" src="http://www.planwallpaper.com/static/images/canberra_hero_image_JiMVvYU.jpg" />
			{% endif %}
		</label><br>
	{% endfor %}
	<input type="submit" value="Favorite">	
</form>
{% endblock %}

music/templates/music/base.html
<head>
	<title>{% block title %}Viber{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>

	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Satisfy">

	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
</head>
<body>
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="{% url 'music:index' %}">Viber</a>
		</div>
		<!-- items -->
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<li class="active">
					<a href="{% url 'music:index' %}">
						<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
						Albums
				</a>
				</li>
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
						</a>
				</li>
			</ul>
			<form class="navbar-form navbar-left" role="search" method="get" action="#">
				<div class="form-group">
					<input type="text" class="form-control" name="q" value="">
				</div>
				<button type="submit" class="btn btn-default">Search</button>
			</form>

			<ul class="nav navbar-nav navbar-right">
				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Album
						</a>
				</li>

				<li class="">
					<a href="#">
						<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
						</a>
				</li>
			</ul>

		</div>
	</div>
</nav>

{% block body %}
{% endblock %}
</body>

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block body%}
	{% if all_album %}
		<h3>Here are all my Albums:</h3>
		<ul>
			{% for album in all_album %}
				<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<h3>You don't have any albums </h3>
	{% endif %}
{% endblock %}